apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    resources:
      requests:
        memory: "150Mi"
        cpu: "250m"
      limits:
        memory: "300Mi"
        cpu: "500m"
      containers:
      - name: spring-boot-app
        image: zakeeakhtar12/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080




